services:
  postgres:
    image: postgres:16-alpine
    container_name: stima-postgres
    environment:
      POSTGRES_USER: stima
      POSTGRES_PASSWORD: stima
      POSTGRES_DB: stima
    ports:
      - "5432:5432"
    volumes:
      - stima_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: stima-redis
    ports:
      - "6379:6379"
    volumes:
      - stima_redis_data:/data

volumes:
  stima_postgres_data:
  stima_redis_data:
