"""Stable product-visible input and resource ceilings."""

from __future__ import annotations

NOTE_INPUT_MAX_CHARS = 50_000
AUDIO_TRANSCRIPT_MAX_CHARS = 100_000
# +2 accounts for the newline separator inserted when transcript and notes are combined.
EXTRACTION_TRANSCRIPT_MAX_CHARS = AUDIO_TRANSCRIPT_MAX_CHARS + NOTE_INPUT_MAX_CHARS + 2
DOCUMENT_TRANSCRIPT_MAX_CHARS = 100_000
CUSTOMER_ADDRESS_MAX_CHARS = 500
LINE_ITEM_DESCRIPTION_MAX_CHARS = 500
LINE_ITEM_DETAILS_MAX_CHARS = 2_000
DOCUMENT_NOTES_MAX_CHARS = 5_000
CONFIDENCE_NOTE_MAX_CHARS = 200
CONFIDENCE_NOTES_MAX_ITEMS = 20
DOCUMENT_LINE_ITEMS_MAX_ITEMS = 50
MAX_AUDIO_CLIPS_PER_REQUEST = 10
MAX_AUDIO_CLIP_BYTES = 10 * 1024 * 1024
MAX_AUDIO_TOTAL_BYTES = 100 * 1024 * 1024
