name: Frontend Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24.0.0'
      - name: Install dependencies
        run: npm ci --prefix frontend
      - name: Frontend verify
        run: make frontend-verify
